import { NextRequest, NextResponse } from 'next/server';
import { BikinPahamPayload, TargetLevel } from '@/types/payload';
import { GoogleGenerativeAI } from '@google/generative-ai';

export const maxDuration = 60;
export const dynamic = 'force-dynamic';

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;
    const targetLevel = formData.get('target_level') as TargetLevel | null;

    if (!file) {
      return NextResponse.json(
        { error: 'File is required' },
        { status: 400 }
      );
    }

    if (!targetLevel || !['SD_SMP', 'SMA_SMK', 'MAHASISWA'].includes(targetLevel)) {
      return NextResponse.json(
        { error: 'Valid target_level required: SD_SMP, SMA_SMK, or MAHASISWA' },
        { status: 400 }
      );
    }

    // Convert file to base64
    const bytes = await file.arrayBuffer();
    const buffer = Buffer.from(bytes);
    const base64File = buffer.toString('base64');
    const mimeType = file.type || 'application/pdf';

    // Level-specific tone instructions
    const toneInstruction = {
      SD_SMP: 'Use simple language, cartoon/daily analogies, child-friendly explanations.',
      SMA_SMK: 'Focus on exam preparation, key formulas, quick tricks, high school level.',
      MAHASISWA: 'Academic tone, deep reasoning, theoretical context, university level.',
    }[targetLevel];

    const systemPrompt = `
You are an expert educational content analyzer. Extract the uploaded document into a structured JSON output strictly following this TypeScript interface:

interface BikinPahamPayload {
  document_meta: {
    title: string;
    target_level: 'SD_SMP' | 'SMA_SMK' | 'MAHASISWA';
  };
  summary_module: Array<{
    topic: string;
    key_points: string[];
    explanation: string;
  }>;
  flashcards: Array<{
    id: number;
    front: string;
    back: string;
  }>;
  quiz_exam: Array<{
    id: number;
    question: string;
    options: string[];
    correct_answer: string;
    explanation: string;
  }>;
}

Guidelines:
- Create 3-5 summary topics covering main document sections.
- Generate 8-12 flashcards with clear front (question/concept) and back (answer/explanation).
- Create 5-10 multiple-choice quiz questions with 4 options each.
- Tone: ${toneInstruction}
- Output ONLY valid JSON, no extra commentary.
`;

    // Call Gemini 2.0 Flash via Google Generative AI SDK
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY environment variable not set');
    }

    const genAI = new GoogleGenerativeAI(apiKey);
    const modelName = process.env.GEMINI_MODEL || 'gemini-1.5-flash';
    const model = genAI.getGenerativeModel({ model: modelName });

    const result = await model.generateContent([
      systemPrompt,
      {
        inlineData: {
          mimeType,
          data: base64File,
        },
      },
    ]);

    const generatedText = result.response.text();
    if (!generatedText) {
      throw new Error('No content generated by Gemini');
    }

    // Extract JSON from response (might be wrapped in markdown code blocks)
    const jsonMatch =
      generatedText.match(/```json\n([\s\S]*?)\n```/) ||
      generatedText.match(/(\{[\s\S]*\})/);
    const jsonStr = jsonMatch ? jsonMatch[1] ?? jsonMatch[0] : generatedText;
    const payload: BikinPahamPayload = JSON.parse(jsonStr);

    // Ensure target_level matches request
    payload.document_meta.target_level = targetLevel;

    return NextResponse.json(payload);
  } catch (error) {
    console.error('Ingestion error:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Unknown ingestion error' },
      { status: 500 }
    );
  }
}
